--- FSAdmin
CREATE USER FSAdmin IDENTIFIED BY Admin;
GRANT CONNECT TO FSAdmin;
GRANT RESOURCE TO FSAdmin;
GRANT CREATE SESSION TO FSAdmin;
GRANT UNLIMITED TABLESPACE TO FSAdmin;
GRANT DBA TO FSAdmin;

--- FSStatistic
CREATE USER FSStatistic IDENTIFIED BY Statistic;
GRANT CONNECT TO FSStatistic;
GRANT RESOURCE TO FSStatistic;
GRANT CREATE SESSION TO FSStatistic;
GRANT SELECT ANY TABLE TO FSStatistic;

