= Arztpraxis

== Team

* Fröller Felix
* Lehner David
* Nikolaus Alexander

== Fachdomäne

Ziel ist es, dem Inhaber einen Überblick seiner Arztpraxis zu gewähren.
Daten über Krankheitsfälle, Patienten, sowie die erbrachten Leistungen seiner Ärzte sollen erfasst werden.
Die Software soll zudem zur Terminfindung für Patienten genutzt werden.

|===
| Entity | Attribute
| Arztpraxis | (PraxisID; PLZ; Ort; Adresse; HausNr)
| Arzt | (ArztID; VName; NName; Titel; ArztTypFK; PraxisFK)
| ArztTyp | (TypID; Name; Beschreibung)
| Patient | (SVN; VName; NName; PLZ; Ort; Adresse; HausNr; Geb.)
| Termin | (TerminID; Datum; Uhrzeit; Dauer; PatientFK; ArztFK)
| Diagnose | (DiagnoseID; BehandlungFK; Name; Beschreibung)
| Rezept | (RezeptID; Verschreibung; Ausstellungsdatum; Preis; PatientFK)
| Behandlung | (BehandlungsID; RezeptFK; DiagnoseFK; Behandlungsart)
|===

== Relevante Queries (SQL)

* Nächster freier Termin
* Kosten für Behandlung
* Patientenliste pro Tag
* Ist ein Termin an bestimmter Uhrzeit/Datum noch frei?
* Krankheitsstatistik für 1 Jahr (Anzahl an Erkrankungen jeweiliger Krankheit pro Monat)
* Durchschnittliche Behandlungszeit
* *Funktionsname:* GetCommonDiagnosesStatistics Verwendung: Rufen Sie diese Funktion auf, um statistische Informationen über häufig gestellte Diagnosen zu erhalten. +
*Funktionalität:* Diese Funktion analysiert die "Diagnose"-Tabelle und gibt eine Liste der am häufigsten gestellten Diagnosen zusammen mit ihrer Häufigkeit aus.

== DDL

[source,sql]
----

CREATE TABLE arztpraxis
(
    praxisid number(20)    NOT NULL,
    plz      varchar2(10)  NOT NULL,
    ort      varchar2(255) NOT NULL,
    adresse  varchar2(255) NOT NULL,
    hausnr   varchar2(10)  NOT NULL,
    CONSTRAINT pk_arztpraxis PRIMARY KEY (praxisid)
);

CREATE TABLE arzttyp
(
    typid        number(20)    NOT NULL,
    name         varchar2(255) NOT NULL,
    beschreibung varchar2(255) NOT NULL,
    CONSTRAINT pk_arzttyp PRIMARY KEY (typid)
);

CREATE TABLE arzt
(
    arztid    number(20)    NOT NULL,
    vname     varchar2(255) NOT NULL,
    nname     varchar2(255) NOT NULL,
    titel     varchar2(50)  NOT NULL,
    arzttypfk number(20)    NOT NULL,
    praxisfk  number(20)    NOT NULL,
    CONSTRAINT pk_arzt PRIMARY KEY (arztid),
    CONSTRAINT fk_arzt_arzttyp FOREIGN KEY (arzttypfk) REFERENCES arzttyp (typid),
    CONSTRAINT fk_arzt_praxis FOREIGN KEY (praxisfk) REFERENCES arztpraxis (praxisid)
);

CREATE TABLE patient
(
    svn     varchar2(20)  NOT NULL,
    vname   varchar2(255) NOT NULL,
    nname   varchar2(255) NOT NULL,
    plz     varchar2(10)  NOT NULL,
    ort     varchar2(255) NOT NULL,
    adresse varchar2(255) NOT NULL,
    hausnr  varchar2(10)  NOT NULL,
    geb     date          NOT NULL,
    CONSTRAINT pk_patient PRIMARY KEY (svn)
);

CREATE TABLE termin
(
    terminid  number(20)   NOT NULL,
    datum     date         NOT NULL,
    uhrzeit   timestamp    NOT NULL,
    dauer     number(20)   NOT NULL,
    patientfk varchar2(20) NOT NULL,
    arztfk    number(20)   NOT NULL,
    CONSTRAINT pk_termin PRIMARY KEY (terminid),
    CONSTRAINT fk_termin_patient FOREIGN KEY (patientfk) REFERENCES patient (svn),
    CONSTRAINT fk_termin_arzt FOREIGN KEY (arztfk) REFERENCES arzt (arztid)
);

CREATE TABLE diagnose
(
    diagnoseid   number(20)    NOT NULL,
    name         varchar2(255) NOT NULL,
    beschreibung varchar2(255) NOT NULL,
    terminfk     number(20)    NOT NULL,
    CONSTRAINT pk_diagnose PRIMARY KEY (diagnoseid),
    CONSTRAINT fk_diagnose_termin FOREIGN KEY (terminfk) REFERENCES termin (terminid)
);

CREATE TABLE rezept
(
    rezeptid          number(20)     NOT NULL,
    verschreibung     varchar2(255)  NOT NULL,
    ausstellungsdatum date           NOT NULL,
    preis             decimal(10, 2) NOT NULL,
    patientfk         varchar2(20)   NOT NULL,
    CONSTRAINT pk_rezept PRIMARY KEY (rezeptid),
    CONSTRAINT fk_rezept_patient FOREIGN KEY (patientfk) REFERENCES patient (svn)
);

CREATE TABLE behandlung
(
    behandlungsid  number(20)    NOT NULL,
    behandlungsart varchar2(255) NOT NULL,
    rezeptfk       number(20)    NOT NULL,
    diagnosefk     number(20)    NOT NULL,
    CONSTRAINT pk_behandlung PRIMARY KEY (behandlungsid),
    CONSTRAINT fk_behandlung_rezept FOREIGN KEY (rezeptfk) REFERENCES rezept (rezeptid),
    CONSTRAINT fk_behandlung_diagnose FOREIGN KEY (diagnosefk) REFERENCES diagnose (diagnoseid)
);

----

== PL/SQL API zur Datenpflege

=== Übersichtsberichte

*Funktionsname:* GeneratePracticeOverviewReport Verwendung: Aufrufen der Funktion um Übersichtsbericht der Praxis. +
*Funktionalität:* Ruft relevante Daten aus verschiedenen Tabellen ab und erstellt einen Übersichtsbericht mit Statistiken zur Patientendemografie, Umsatz, häufigen Diagnosen und der Leistung der Ärzte.

=== Terminvereinbarung

*Funktionsname:* ScheduleAppointment Verwendung: Prozedur mit Patienten und Termindetails aufrufen, um einen neuen Termin zu planen. Wenn es den Patienten noch nicht gibt, wird er angelegt+
*Funktionalität:* Überprüft die Verfügbarkeit des Arztes, erstellt einen neuen Termin-Datensatz in der "Termin"-Tabelle 

=== Verfolgung medizinischer Leistungen

*Funktionsname:* RecordMedicalService Verwendung: Rufen Sie diese Prozedur mit Patienten-, Arzt-, Diagnose- und Rezeptdetails auf, um medizinische Dienstleistungen zu erfassen. +
*Funktionalität:* Erstellt Datensätze in verschiedenen Tabellen, um medizinische Dienstleistungen, zugehörige Diagnosen und Rezepte zu verfolgen und stellt sicher, dass eine umfassende Patientenhistorie beibehalten wird.

=== Logging Triggers

* Terminbezogene Updates (Absagen, Buchungen, Verschiebungen)
** Use Case: Hilft, Termine zu organisieren, und um zu wissen, wann Patienten kommen, und wann Ärzte frei sind.
* Updates, wenn sich Daten eines Patienten ändern (außer SVN)
** Use Case: Ermöglicht die Überwachung aller Änderungen an Patientendaten
* Error und Exception Logging Trigger.
** Bei Fehler (error codes, exceptions etc.) wird ein Dateneintrag geloggt, mit Fehler und Timestamp.

=== ERD:

[plantuml,cld,png]
----
include::plantuml/cld.puml[]
----
